project:
  type: book

book:
  title: "Metaproteomics Analysis"
  author: "Johan S. Sáenz & Bibiana Rios"
  date: "5/28/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - run_quality.qmd
    - taxonomy_nmds.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      - cosmo
      - style.css
    code-link: true