# Run quality

In summary, this book has no content whatsoever.

1.  **Load libraries**

```{r echo=FALSE}
library(tidyverse)
library(patchwork)
library(here)
library(gt)
```

2.  **Load data frame**

```{r}
quality <- read_tsv("rawdata/final_summary.tsv")
```

3.  **Create a table**

```{r echo=FALSE}
table <- quality %>% 
  select(-Experiment) %>% 
  filter(`Raw file` != "Total") %>% 
  pivot_longer(cols = -1, names_to = "Variable", values_to = "value") %>% 
  group_by(Variable) %>% 
  summarise(Max = round(max(value), 1),
            Min = round(min(value), 1),
            Mean = round(mean(value), 1),
            Sd = round(sd(value), 1))
```

```{r}
table %>% 
  gt() %>% 
  tab_stubhead(label = "landmass") %>% 
  cols_label()
```

4. **Create a histogram of the identified MS/MS**

```{r}
percentage <- quality %>%
  ggplot(aes(x = `MS/MS Identified [%]`)) +
  geom_histogram(binwidth = 2) +
  geom_vline(xintercept= 55.7, linetype = "dashed", 
             color = "red", linewidth = 1) +
  scale_x_continuous(breaks = seq(0, 75, by = 5)) +
  scale_y_continuous(breaks = seq(0, 5, by = 1),
                     expand = c(0, 0)) +
  labs(y = "Number of samples") +
  theme_classic()

percentage
```

5. **Create a histogram of the identified peptide sequences**

```{r}
peptides <- quality %>%
  filter(`Raw file` != "Total") %>% 
  mutate(`Raw file` =str_remove(`Raw file`, "Seifert_Hammel_Nr")) %>% 
  ggplot(aes(x = `Peptide Sequences Identified`)) +
  geom_histogram(binwidth = 1000) +
  geom_vline(xintercept = 16630, linetype = "dashed", 
             color = "red", linewidth = 1) +
  scale_x_continuous(breaks = seq(0, 30231, by = 2500)) +
  scale_y_continuous(breaks = seq(0, 20, by = 2),
                     expand = c(0, 0)) +
  labs(y = "Number of samples") +
  theme_classic()

peptides
```


6. **Create a compose plot**

```{r echo=FALSE}
(peptides /percentage)  + 
  plot_annotation(tag_levels = 'A')
```
